//
// Created by user on 05.12.2017.
//

#ifndef OPENGL_SHADERTYPE_H
#define OPENGL_SHADERTYPE_H


enum ShaderTypes {
    VERTEX = GL_VERTEX_SHADER,
    FRAGMENT = GL_FRAGMENT_SHADER,
    GEOMETRY = GL_GEOMETRY_SHADER,
    TESS_CONTROL = GL_TESS_CONTROL_SHADER,
    TESS_EVALUATION = GL_TESS_EVALUATION_SHADER,
    COMPUTE = GL_COMPUTE_SHADER
};


#endif //OPENGL_SHADERTYPE_H
